spring:
  application:
    name: fortune-eureka
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
  server:
    renewal-percent-threshold: 0
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
---
spring:
  profiles:
  - local
server:
  port: 8761